name: 'Sentry Release'
description: 'GitHub Action for creating a release on Sentry'
author: 'Sentry'
inputs:
  environment:
    description: 'Set the environment for this release. E.g. "production" or "staging".'
    required: true
  sourcemaps:
    description: 'Space-separated list of paths to JavaScript sourcemaps. Omit to skip uploading sourcemaps.'
    required: false
  finalize:
    description: 'When false, omit marking the release as finalized and released.'
    default: true
  started_at:
    description: 'Unix timestamp of the release start date.'
    required: false
  version_prefix:
    description: 'TODO'
    required: false
runs:
  using: 'docker'
  image: 'docker://sentryintegrations/sentry-github-action-release:latest'
branding:
  icon: 'triangle'
  color: 'purple'
